exports.SOMETHING_WENT_WRONG = "Something went wrong";
exports.INVALID_CREDENTIALS = "Invalid credentials";
exports.WRONG_PASSWORD = "Wrong Password";
exports.JWT_DECODE_ERR = "Invalid token";
exports.USER_NOT_FOUND_ERR = "User not found";
exports.LOGIN_FAILED = "Login Failed";
exports.MESSGE_SENDING_FAILED = "Unable to send this message"
exports.OTP_EXPIRING_ERR = "OTP expired";
exports.WRONG_OTP_ERR = "Invalid OTP";
exports.DATABASE_ERR = "Database Error Occured";
exports.IMAGE_PROCESSING_ERR = "Could not process the image";